#Site settings
title: The jekyll way 
email: thejekyllway@gmail.com
description: 
baseurl: "/"
url: "http://thejekyllway.github.io"

#Social network
github_username: thejekyllway
twitter_username: thejekyllway

#Build settings
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
data_dir: ./_data
exclude: ["node_modules", "gulpfile.js", "package.json"]
paginate_path: 'page:num'

#Gems
gems:
	- jekyll-paginate

#Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: true
